foodorder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('content/', include('content.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('error/', views.error, name='error'),

    path('products/', views.category_products, name='products'),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('content/<int:id>/<slug:slug>', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('restaurant/<int:id>', views.restaurant, name='restaurant'),


    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('sss/', views.faq, name='faq'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    ]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('orders/', views.orders, name='orders'),
    path('shopcart/', views.shopcart, name='shopcart'),
    path('orderdetail/<int:id>/', views.orderdetail, name='orderdetail'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>/', views.deletecomment, name='deletecomment'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),
    path('contentedit/<int:id>/', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>/', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>/', views.contentaddimage, name='contentaddimage'),

    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )

    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=20)
    smtpport = models.CharField(blank=True, max_length=10)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=150)
    instagram = models.CharField(blank=True, max_length=150)
    twitter = models.CharField(blank=True, max_length=150)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'İsim Soyisim'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Konu'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Mail adresiniz'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Mesajınız', 'rows': '5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    adress = models.CharField(blank=True, max_length=20)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return '[ ' + self.user.username + ' ] ' + self.user.first_name + ' ' + self.user.last_name

    def image_tag(self):
        return mark_safe('<img src="{}" height= "50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'adress', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )

    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question

user/models.py
from django.db import models

# Create your models here.

user/views.py
import concurrent.futures
from tkinter import Menu
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.mail import message
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from home.models import UserProfile
from content.models import Content, Menu, ContentForm, ContentImageForm, CImages
from order.models import Order, OrderProduct, ShopCart
from product.models import Category, Comment, Restaurant
from user.forms import UserUpdateForm, ProfileUpdateForm


@login_required(login_url='/login')
def index(request):
    category = Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    restaurant1 = Restaurant.objects.all()

    context = {
        'category': category,
        'restaurant1': restaurant1,
        'profile': profile
    }
    return render(request, 'user_profile.html', context)


@login_required(login_url='/login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            message.success(request, 'Hesabın Güncellendi')
            return redirect('/user')

    else:
        category = Category.objects.all()
        restaurant1 = Restaurant.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form,
            'restaurant1': restaurant1,
        }
        return render(request, 'user_update.html', context)


@login_required(login_url='/login')
def addcontent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            currentuser = request.user
            data = Content()
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.type = form.cleaned_data['type']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()
            message.success(request, 'içerik başarı ile eklendi')
            return HttpResponseRedirect('/user/contents')

        else:
            message.success(request, 'Hata:' + str(form.errors))
            return HttpResponseRedirect('/user/addcontent')

    else:
        category = Category.objects.all()
        restaurant1 = Restaurant.objects.all()
        menu = Menu.objects.all()
        form = ContentForm()
        context = {
            'menu': menu,
            'category': category,
            'form': form,
            'restaurant1': restaurant1,
        }
        return render(request, 'user_addcontent.html', context)


@login_required(login_url='/login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Hesap bilgileri güncellendi!')
            return redirect('/user')

    else:
        category = Category.objects.all()
        restaurant1 = Restaurant.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form,
            'restaurant1': restaurant1,
        }
        return render(request, 'user_update.html', context)


@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Şifreniz Başarı ile Güncellenmiştir!')
            return redirect('change_password')
        else:
            messages.error(request, 'Şifre Degiştirme Başarısız Lütfen Tekrar Deneyin')

    else:
        category = Category.objects.all()
        restaurant1 = Restaurant.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html',
                      {'form': form, 'category': category, 'restaurant1': restaurant1})


@login_required(login_url='/login')
def orders(request):
    category = Category.objects.all()
    current_user = request.user
    restaurant1 = Restaurant.objects.all()
    profile = UserProfile.objects.get(user_id=current_user.id)
    orders = Order.objects.filter(user_id=current_user.id)

    context = {
        'category': category,
        'orders': orders,
        'profile': profile,
        'restaurant1': restaurant1,
    }
    return render(request, 'user_orders.html', context)


@login_required(login_url='/login')
def orderdetail(request, id):
    category = Category.objects.all()
    restaurant1 = Restaurant.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    order = Order.objects.get(user_id=current_user.id, id=id)
    orderitems = OrderProduct.objects.filter(order_id=id)

    context = {
        'category': category,
        'order': order,
        'orderitems': orderitems,
        'restaurant1': restaurant1,
        'profile': profile,
    }
    return render(request, 'user_order_detail.html', context)


@login_required(login_url='/login')
def comments(request):
    category = Category.objects.all()
    restaurant1 = Restaurant.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    comments = Comment.objects.filter(user_id=current_user.id)

    context = {
        'category': category,
        'restaurant1': restaurant1,
        'comments': comments,
        'profile': profile,
    }
    return render(request, 'user_comments.html', context)


@login_required(login_url='/login')
def deletecomment(request, id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()

    return HttpResponseRedirect('/user/comments')


@login_required(login_url='/login')
def contentdelete(request, id):
    current_user = request.user
    Content.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'İçerik Silindi.')
    return HttpResponseRedirect('/user/contents')


@login_required(login_url='/login')
def addcontent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = Content()
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.type = form.cleaned_data['type']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()
            messages.success(request, 'içeriginiz Başarı ile Eklenmiştir.')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.success(request, 'İçerik hatası:' + str(form.errors))
            return HttpResponseRedirect('/user/addcontent')


    else:
        category = Category.objects.all()
        menu = Menu.objects.all()
        restaurant1 = Restaurant.objects.all()
        form = ContentForm()
        context = {
            'menu': menu,
            'category': category,
            'form': form,
            'restaurant1': restaurant1,
        }
        return render(request, 'user_addcontent.html', context)


@login_required(login_url='/login')
def contentedit(request, id):
    content = Content.objects.get(id=id)
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES, instance=content)
        if form.is_valid():
            form.save()
            messages.success(request, ' İçerigin Başarı ile Güncellendi.')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.success(request, 'içerik Ekleme Hatası' + str(form.errors))
            return HttpResponseRedirect('/user/contentedit/' + str(id))

    else:
        category = Category.objects.all()
        restaurant1 = Restaurant.objects.all()
        menu = Menu.objects.all()
        form = ContentForm(instance=content)
        context = {
            'category': category,
            'form': form,
            'menu': menu,
            'restaurant1': restaurant1,
        }
    return render(request, 'user_addcontent.html', context)


@login_required(login_url='/login')
def contentdelete(request, id):
    current_user = request.user
    Content.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'İçerik Silindi...')
    return HttpResponseRedirect('/user/contents')


@login_required(login_url='/login')

user/templates/change_password.html
{% extends "homebase.html" %}
{% load static %}
{% block  title %} {{ profile.user_name }} Profili {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %}{{ setting.description }} {% endblock %}
{% block  head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block  sidebar %}
    {% include "sidebar.html" %}
{% endblock %}

{% block  content %}
    <section>
        <div class="block">
            <div class="fixed-bg" style="background-image: url({% static '/images/topbg.jpg' %});"></div>
            <div class="restaurant-searching text-center">
                <div class="col-md-12 col-sm-12 col-lg-12">
                    <div class="page-title-inner">
                        <h1 itemprop="headline">KULLANICI PANELİNE HOŞGELDİNİZ</h1>
                        <span>---------------------------------------------------------------</span>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <div class="bread-crumbs-wrapper">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/" title="" itemprop="url">Ana Sayfa</a></li>
                <li class="breadcrumb-item active">Profil</li>
            </ol>
        </div>
    </div>

    <section>
        <div class="block less-spacing gray-bg top-padd30">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-lg-12">
                        <div class="sec-box">
                            <div class="dashboard-tabs-wrapper">
                                <div class="row">
                                    <div class="col-md-4 col-sm-12 col-lg-4">
                                        <div class="profile-sidebar brd-rd5 wow fadeIn" data-wow-delay="0.2s">
                                            {% include "user_panel.html" %}
                                        </div>
                                    </div>
                                    <div class="col-md-8 col-sm-12 col-lg-8">
                                        <div class="tab-content">

                                        {% if messages %}
                                            {% for message in messages %}
                                                <div style="color: #d43f3a; font-size: medium ">
                                                {{ message| safe }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                            <form method="post">
                                                {% csrf_token %}
                                                {% for field in form %}
                                                    <p>
                                                    {{ field.label_tag }}<br>
                                                    {{ field }}
                                                    {% if field.help.text %}
                                                        <small style="color:grey">{{ field.help.text }}</small>
                                                    {% endif %}
                                                    {% for error in field.errors %}
                                                        <p style="...">{{ error }}</p>>
                                                        {% endfor %}
                                                    </p>
                                                {% endfor %}
                                            <button type="submit">Degişiklikleri Kaydet</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- Section Box -->
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>İçerik Galerisi</title>
</head>
<body>
<h2>{{ content.title }}</h2>
<hr>

{% if messages %}
    {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="content_id" id="id_content_id" value="{{ content.id }}"><br>
    <label for="id_title">Başlık</label>
    <input type="text" name="title" class="input" placeholder="Başlık" maxlength="50" id="id_title" ">
    <br><br><label for="id_title">Resim</label>
    <input type="file" name="image" class="input" placeholder="Resim" accept="image/*" maxlength="50" id="id_image" ">
    <br><br><button class="button" type="submit">Resmi Yükle</button>
</form>
<hr>
<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200">

{% endfor %}

</body>
</html>

user/templates/user_addcontent.html
{% extends "homebase.html" %}
{% load static %}
{% block  title %} İÇERİK PANELİ {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %}{{ setting.description }} {% endblock %}
{% block  head %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block  sidebar %}
    {% include "sidebar.html" %}
{% endblock %}

{% block  content %}
    <section>
        <div class="block">
            <div class="fixed-bg" style="background-image: url({% static '/images/topbg.jpg' %});"></div>
            <div class="restaurant-searching text-center">
                <div class="col-md-12 col-sm-12 col-lg-12">
                    <div class="page-title-inner">
                        <h1 itemprop="headline">İÇERİK PANELİNE HOŞGELDİNİZ</h1>
                        <span>---------------------------------------------------------------</span>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <div class="bread-crumbs-wrapper">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/" title="" itemprop="url">Ana Sayfa</a></li>
                <li class="breadcrumb-item active">İçerikler</li>
            </ol>
        </div>
    </div>

    <section>
        <div class="block less-spacing gray-bg top-padd30">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-lg-12">
                        <div class="sec-box">
                            <div class="dashboard-tabs-wrapper">
                                <div class="row">
                                    <div class="col-md-3 col-sm-12 col-lg-3">
                                        <div class="profile-sidebar brd-rd5 wow fadeIn" data-wow-delay="0.2s">
                                            {% include "user_panel.html" %}
                                        </div>
                                    </div>
                                    <div class="col-md-9 col-sm-12 col-lg-9">
                                        <h4 class="title1-inner">İçerik Ekle</h4>
                                        <div class="content">
                                            <form method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <fieldset class="form-group">
                                                    {{ form.media }}
                                                    {{ form.as_p }}
                                                </fieldset>
                                                <button class="red-bg brd-rd3" type="submit">KAYDET</button>
                                            </form>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}
{% load static %}
{% block  title %} YORUMLARIM {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %}{{ setting.description }} {% endblock %}
{% block  head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block  sidebar %}
    {% include "sidebar.html" %}
{% endblock %}

{% block  content %}
    <section>
        <div class="block">
            <div class="fixed-bg" style="background-image: url({% static '/images/topbg.jpg' %});"></div>
            <div class="restaurant-searching text-center">
                <div class="col-md-12 col-sm-12 col-lg-12">
                    <div class="page-title-inner">
                        <h1 itemprop="headline">KULLANICI PANELİNE HOŞGELDİNİZ</h1>
                        <span>---------------------------------------------------------------</span>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <div class="bread-crumbs-wrapper">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/" title="" itemprop="url">Ana Sayfa</a></li>
                <li class="breadcrumb-item active">Yorumlarım</li>
            </ol>
        </div>
    </div>

    <section>
        <div class="block less-spacing gray-bg top-padd30">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-lg-12">
                        <div class="sec-box">
                            <div class="dashboard-tabs-wrapper">
                                <div class="row">
                                    <div class="col-md-4 col-sm-12 col-lg-4">
                                        <div class="profile-sidebar brd-rd5 wow fadeIn" data-wow-delay="0.2s">
                                            {% include "user_panel.html" %}
                                        </div>
                                    </div>
                                    <div class="col-md-8 col-sm-12 col-lg-8">
                                        <table class="table table-striped table-hover">
                                            <thead>
                                            <tr>
                                                <th>ÜRÜN</th>
                                                <th>DERECE</th>
                                                <th>KONU</th>
                                                <th>YORUM</th>
                                                <th>DURUM</th>
                                                <th>TARİH</th>
                                                <th>DETAY</th>
                                            </tr>
                                            </thead>

                                             {% for rs in comments %}
                                            <tr>

                                                <td><a href="/product/{{ rs.product_id }}/{{ rs.product.slug }}">{{ rs.product.title }}</td></a>
                                                <td>
                                                  <span style="text-transform: uppercase"> {{ rs.rate }}</span></a></td>
                                                <td><span style="text-transform: uppercase">{{ rs.subject }}</span></td>
                                                <td>{{ rs.comment }}</td>
                                                <td><span class="status text-success">&bull;</span> {{ rs.status }}</td>
                                                <td>{{ rs.create_at }}</td>
                                                <td><span style="text-transform: uppercase">
                                                    <a href="/user/deletecomment/{{ rs.id }}" onclick="return confirm('Yorumu Silmek İstedigine Emin misin?')">YORUMU SİL</a>
                                                </span>
                                                </td>
                                            </tr>
                                            {% endfor %}

                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}